# Generated by Django 4.0 on 2021-12-15 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название игры', max_length=256, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('gift_cost_limit', models.CharField(choices=[('None', 'без ограничений'), ('UPTO500', 'до 500 рублей'), ('500_1000', '500-1000 рублей'), ('1000_2000', '1000-2000 рублей')], default='None', max_length=50, verbose_name='Стоимость подарка')),
                ('registration_deadline', models.DateField(verbose_name='Дата окончания регистрации')),
                ('gift_sending_deadline', models.DateField(verbose_name='Отправить подарок до')),
                ('administrators', models.ManyToManyField(blank=True, related_name='managed_games', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_games', to='accounts.user')),
                ('participants', models.ManyToManyField(blank=True, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_gift_sent', models.BooleanField(default=False, verbose_name='Подарок отправлен?')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='games.game')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givers', to='accounts.user')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
    ]
