# Generated by Django 4.0 on 2021-12-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_is_participants_shuffled'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_creator_participant',
            field=models.BooleanField(default=True, help_text='Будет ли создатель игры сам принимать в ней участие?', verbose_name='Буду участником?'),
        ),
    ]
