# Generated by Django 4.0 on 2021-12-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_place_alter_game_is_creator_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='place',
            field=models.CharField(blank=True, default='', help_text='Оставьте поле пустым, если игра проводится через email-рассылку', max_length=256, verbose_name='Место встречи'),
            preserve_default=False,
        ),
    ]
