# Generated by Django 4.0 on 2021-12-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_wishlist_alter_user_address'),
        ('games', '0007_game_is_online_game_your_gift_cost_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to='games.game')),
                ('items', models.ManyToManyField(blank=True, to='accounts.WishListItem', verbose_name='Пожелания к подарку')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Лист желаний',
                'verbose_name_plural': 'Листы желаний',
                'unique_together': {('user', 'game')},
            },
        ),
    ]
