# Generated by Django 4.0 on 2021-12-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_wishlist_alter_user_address'),
        ('games', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElidiblePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elidible_pairs', to='games.game')),
                ('user_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user')),
                ('user_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Пара-исключение',
                'verbose_name_plural': 'Пары-исключения',
            },
        ),
    ]
