# Generated by Django 4.0 on 2021-12-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_wishlist_alter_user_address'),
        ('games', '0009_elidiblepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elidiblepair',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user', verbose_name='Участник 1'),
        ),
        migrations.AlterField(
            model_name='elidiblepair',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user', verbose_name='Участник 2'),
        ),
        migrations.AlterUniqueTogether(
            name='elidiblepair',
            unique_together={('user_1', 'game'), ('user_2', 'game')},
        ),
    ]
